#!/usr/bin/env node
/**
 * Single-source build for the Flipper fork analysis (graph model).
 *
 *   data/features.json    ← per-fork capability matrix (tree of items)   ┐ both
 *   data/structure.json   ← graph layer: taxonomy + structural/FAP nodes ┘ hand-edited
 *        │  merge + validate
 *        ├─►  data/features.js   (window.FEATURES = {forks,lineage,taxonomy,nodes,edges,tree})
 *        └─►  FEATURE-TREE.md    (matrix + relationship appendix)
 *
 * Everything is a NODE; edges (in structure.json) express how things relate
 * (protocol→modulation/encoding/cipher, NFC product→layer→radio, attack→cipher,
 * capability→FAP). The browsable tree is DERIVED from nodes grouped by domain.
 *
 *   node analysis/build.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.join(HERE, 'data');
const F_JSON = path.join(DATA, 'features.json');
const S_JSON = path.join(DATA, 'structure.json');
const JS_OUT = path.join(DATA, 'features.js');
const MD_OUT = path.join(HERE, 'FEATURE-TREE.md');
const HTML = path.join(HERE, 'feature-explorer.html');

const features = JSON.parse(fs.readFileSync(F_JSON, 'utf8'));
const structure = JSON.parse(fs.readFileSync(S_JSON, 'utf8'));
const hints = structure.typeHints || {};

/* ---------- 1. flatten the capability tree into typed nodes ---------- */
function inferType(domain, group, id) {
  if (hints[id]) return hints[id];
  const g = (group || '').toLowerCase();
  if (g.includes('protocol coverage')) return domain === 'NFC' ? 'product' : 'protocol';
  if (g.includes('rolling-code')) return 'capability';
  if (g.includes('region')) return 'capability';
  if (g.includes('tooling')) return 'capability';
  if (g.includes('key recovery') || g.includes('attack')) return 'attack';
  if (g.includes('parser')) return 'parser';
  if (g.includes('app') || g.includes('plugin') || g.includes('fap')) return 'app';
  if (domain === 'Security posture') return 'security';
  return 'capability';
}

const nodes = [];
for (const cat of features.tree)
  for (const g of cat.groups)
    for (const it of g.items)
      nodes.push({ ...it, type: it.type || inferType(cat.cat, g.name, it.id), domain: cat.cat, group: g.name });

/* ---------- 2. merge structural + FAP nodes ---------- */
for (const n of (structure.nodes || [])) nodes.push(n);

/* ---------- 3. validate ids + edges ---------- */
const ids = new Set();
const dupes = [];
for (const n of nodes) { if (ids.has(n.id)) dupes.push(n.id); ids.add(n.id); }
const edges = structure.edges || [];
const badEdges = edges.filter((e) => !ids.has(e.from) || !ids.has(e.to));
const relIds = new Set((structure.taxonomy?.relTypes || []).map((r) => r.id));
const badRels = edges.filter((e) => !relIds.has(e.rel));
if (dupes.length) console.warn('⚠ duplicate node ids:', [...new Set(dupes)].join(', '));
if (badEdges.length) { console.warn('⚠ edges referencing unknown node ids:'); badEdges.forEach((e) => console.warn(`   ${e.from} -[${e.rel}]-> ${e.to}`)); }
if (badRels.length) console.warn('⚠ edges with unknown rel:', [...new Set(badRels.map((e) => e.rel))].join(', '));
if (!dupes.length && !badEdges.length && !badRels.length) console.log(`• validated ${nodes.length} nodes, ${edges.length} edges — OK`);

/* ---------- 4. derive the browsable tree (domain → group → items) ---------- */
const domainMeta = new Map((structure.domains || []).map((d) => [d.name, d.bar]));
const domainOrder = (structure.domains || []).map((d) => d.name);
const byDomain = new Map();
for (const n of nodes) {
  if (!byDomain.has(n.domain)) byDomain.set(n.domain, new Map());
  const groups = byDomain.get(n.domain);
  if (!groups.has(n.group)) groups.set(n.group, []);
  groups.get(n.group).push(n);
}
const domainsSorted = [...byDomain.keys()].sort((a, b) => {
  const ia = domainOrder.indexOf(a), ib = domainOrder.indexOf(b);
  return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib);
});
const tree = domainsSorted.map((cat) => ({
  cat, bar: domainMeta.get(cat) || 'var(--mut)',
  groups: [...byDomain.get(cat)].map(([name, items]) => ({ name, items })),
}));

const out = {
  meta: features.meta,
  forks: features.forks,
  lineage: features.lineage,
  taxonomy: structure.taxonomy,
  nodes, edges, tree,
};

/* ---------- 5. emit data/features.js ---------- */
fs.writeFileSync(JS_OUT,
  '/* GENERATED by analysis/build.mjs from data/features.json + data/structure.json — do not edit. */\n' +
  'window.FEATURES = ' + JSON.stringify(out) + ';\n');
console.log('• wrote data/features.js');

/* ---------- 6. emit FEATURE-TREE.md ---------- */
const glyph = (v) => v === 'yes' ? '✓' : v === 'no' ? '✗' : v === 'partial' ? '~' : v;
const safe = (s) => String(s || '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
const label = (id) => { const n = nodes.find((x) => x.id === id); return n ? n.label : id; };
const today = new Date().toISOString().slice(0, 10);
const count = nodes.length;

let md = '# Flipper FW Feature Tree — Completeness Matrix\n\n';
md += '> **GENERATED from `data/features.json` + `data/structure.json` — do not hand-edit. Run `node analysis/build.mjs`.**\n';
md += '> Legend: ✓ present · ✗ absent · ~ partial/variant · *value* = literal. Columns **O**/**U**/**R**/**M** = Official / Unleashed / RogueMaster / Momentum.\n\n';
md += '| Code | Fork | Repo | Role |\n|---|---|---|---|\n';
features.forks.forEach((f) => { md += `| ${f.k} | ${f.name} | ${f.ab} | ${safe(f.role)} |\n`; });
md += '\n';
let ci = 0;
for (const cat of tree) {
  ci++; md += `\n## ${ci}. ${cat.cat}\n`;
  let gi = 0;
  for (const g of cat.groups) {
    gi++; md += `\n### ${ci}.${gi} ${g.name}\n\n`;
    md += '| Feature | Type | Implements | O | U | R | M | Provenance |\n|---|---|---|:--:|:--:|:--:|:--:|---|\n';
    for (const it of g.items) {
      const name = safe(it.label) + (it.file ? ` \`${safe(it.file)}\`` : '');
      md += `| ${name} | ${it.type} | ${safe(it.desc)} | ${glyph(it.s.O)} | ${glyph(it.s.U)} | ${glyph(it.s.R)} | ${glyph(it.s.M)} | ${safe(it.prov)} |\n`;
    }
  }
}
/* relationship appendix */
md += `\n---\n\n## Relationships (structural graph)\n\n`;
md += 'How capabilities decompose into shared primitives. ' + edges.length + ' edges.\n\n';
const relList = (structure.taxonomy?.relTypes || []);
for (const rt of relList) {
  const es = edges.filter((e) => e.rel === rt.id);
  if (!es.length) continue;
  md += `\n**${rt.label}** (\`${rt.id}\`)\n\n`;
  for (const e of es) md += `- ${safe(label(e.from))} → ${safe(label(e.to))}\n`;
}
md += `\n---\n_Built ${today} · ${count} nodes (${features.tree.reduce((n, c) => n + c.groups.reduce((m, g) => m + g.items.length, 0), 0)} capabilities + ${(structure.nodes || []).length} structural/FAP) · ${edges.length} relations. See \`PROVENANCE.md\` and \`feature-explorer.html\`._\n`;
fs.writeFileSync(MD_OUT, md);
console.log(`• wrote FEATURE-TREE.md (${count} nodes, ${edges.length} edges)`);

/* ---------- 7. ensure HTML loads data/features.js ---------- */
const BANNER_DATA = '/* ============================ DATA MODEL ============================ */';
const BANNER_RENDER = '/* ============================ RENDER ============================ */';
const STUB = [BANNER_DATA,
  '/* Sourced from data/features.js — the single source of truth (run analysis/build.mjs). */',
  'const FEATURES = (typeof window!=="undefined" && window.FEATURES) || {forks:[],tree:[],nodes:[],edges:[],taxonomy:{},lineage:{nodes:[],edges:[]}};',
  'const FORKS = FEATURES.forks;',
  'const FCOL = Object.fromEntries(FORKS.map(f=>[f.k,f.color]));',
  'const DATA = FEATURES.tree;',
  'const LIN = FEATURES.lineage;', ''].join('\n');
let html = fs.readFileSync(HTML, 'utf8');
let patched = false;
const s = html.indexOf(BANNER_DATA), e = html.indexOf(BANNER_RENDER);
if (s >= 0 && e >= 0 && html.slice(s, e).trim() !== STUB.trim()) { html = html.slice(0, s) + STUB + '\n' + html.slice(e); patched = true; }
if (!html.includes('<script src="data/features.js"')) {
  const sidx = html.lastIndexOf('<script>', html.indexOf(BANNER_DATA));
  html = html.slice(0, sidx) + '<script src="data/features.js"></script>\n' + html.slice(sidx);
  patched = true;
}
if (patched) { fs.writeFileSync(HTML, html); console.log('• patched feature-explorer.html'); }
else console.log('• feature-explorer.html already wired');
console.log('done.');
